---

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

rules:
  no-console: 0
  indent:
    - 2

# https://github.com/babel/babel-eslint
parser: babel-eslint


extends:
  - 'airbnb-base'
